apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: actual
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: actual
    spec:
      containers:
      - name: actual
        image: actual-server
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 5006
        env:
        - name: NODE_ENV
          value: production
        volumeMounts:
        - name: data
          mountPath: /data
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: actual-data
